#!/bin/bash

BRANCH=$(git rev-parse --abbrev-ref HEAD)
PROTECTED_BRANCHES="^(main|develop)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo -e "Cannot push to remote $BRANCH branch, please create your own branch and use PR."
  exit 1
fi

exit 0