name: publish

on:
  push:
    branches: [ main ]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}    
      - name: Build-Push docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/predragdraganovic/apdf-creator:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
